### PR TITLE
Add transform E2E tests

### PR DESCRIPTION
**Pull request by canni**
This touches almost all codepaths

### CODE REVIEW

**Comment by canni** [comment]
This depends on #4

**Comment by bmcorser** [comment]
For the concat case, can you add a "there and back again" test; kind of a regression for the previous buggy behaviour

**Comment by bmcorser** [comment]
Also these aren't `tier0` tests since they don't touch the OData test service, nor are they `bau` tests since they don't run any `bau` code. Please move them to [`test/unit`](https://github.com/uktrade/data-hub-korben/tree/master/test/unit)

**Comment by bmcorser** [comment]
Probably `test/unit/test_etl.py` would be an appropriate module name.

**Comment by uktitools** [comment]
Can one of the admins verify this patch?

**Pull request merged**
